# Generated by Django 4.2.11 on 2024-04-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rol',
        ),
    ]
