# Generated by Django 4.2.11 on 2024-04-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAPP', '0002_remove_person_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CrudAPP.rol'),
        ),
    ]
