# Generated by Django 4.2.11 on 2024-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAPP', '0003_person_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
