# Generated by Django 4.2.11 on 2024-04-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudAPP', '0004_person_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='order',
        ),
    ]
